routes/web.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use Exception;
use Illuminate\Support\Facades\Route;

/* 
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




// Auth::routes();

Route::post('/changeLang', function () {
    session()->put('phplang', request()->get('lang'));
    app()->setLocale(request()->get('lang'));
    return redirect()->back()->withInput();
})->name('changeLang');

// Route::get('/', [LoginController::class, 'showLoginForm']);
// Route::get('/login', [LoginController::class, 'showLoginForm']);
Route::get('/', [HomeController::class, 'showLogin']);
Route::get('/login', [HomeController::class, 'showLogin']);
Route::post('/dologin', [HomeController::class, 'dologin'])->name('dologin');
Route::post('login/google', [LoginController::class, 'googleLogin'])->name('googleLogin');
Route::get('/register', [RegisterController::class, 'showRegister'])->name('regitser');
Route::get('/allreg', [RegisterController::class, 'allreg']);
Route::post('/register', [RegisterController::class, 'register'])->name('doregister');


Route::get('HomeController/getVehicle', [HomeController::class, 'getVehicle']);

Route::post('userIds', [HomeController::class, 'getApi'])->name('ajax.apiKeyAcess');
Route::post('userIdsss', [HomeController::class, 'getDealer'])->name('ajax.dealerAcess');
Route::post('userIdss', [HomeController::class, 'getFcode'])->name('ajax.fcKeyAcess');
Route::post('userIP', [HomeController::class, 'getUserIP'])->name('ajax.userIP');

Route::get('loginpass/{param}/{param1}/{param2}', [HomeController::class, 'byPassUsers']);
Route::get('switchLogin/{param}', [HomeController::class, 'switchLogin']);
Route::post('doLoginTry', [HomeController::class, 'doLogin1'])->name('ajax.doLoginTry');
// Route::post('login', array('before' => 'csrf', 'uses' => 'HomeController::class,doLogin]);
Route::get('login1', [HomeController::class, 'doLogin']);

Route::post('mobleverify', [HomeController::class, 'mobileVerify'])->name('ajax.mobleverisy');
Route::post('cancel', [HomeController::class, 'otpcancel'])->name('ajax.cancel');
Route::post('resendbtn', [HomeController::class, 'resendftn'])->name('ajax.resent');
Route::post('otpverify', [HomeController::class, 'otpverify'])->name('ajax.otpverify');

Route::post('getApiKeys', [HomeController::class, 'getApi']);
Route::post('fileUpload', [HomeController::class, 'fileUpload']);
Route::post('getFiles', [HomeController::class, 'getFileNames']);
Route::get('aUthName', [HomeController::class, 'authName']);
Route::get('dealerName', [HomeController::class, 'getDealerName']);
Route::get('logout', [HomeController::class, 'doLogout'])->name('logout');

Route::get('honda9964', [HomeController::class, 'admin']);
Route::get('adhocMail', [HomeController::class, 'adhocMail']);

Route::post('sendAdhocMail', ['before' => 'csrf', HomeController::class, 'sendAdhocMail']);

Route::get('ipAddressManager', [HomeController::class, 'ipAddressManager']);

Route::get('reverseGeoLocation', [HomeController::class, 'reverseGeoLocation']);

Route::get('nearByVehicles', [HomeController::class, 'nearByVehicles']);


Route::middleware("adminauth")->group(function () {

    Route::get('/lang/{lang}', function($lang){
        app()->setLocale($lang);
        return redirect()->back();
    });
    Route::get('home', [HomeController::class, 'index'])->name('home');

    Route::get('dashboard', [DashBoardController::class, 'index'])->name('dashboard');

    // BusinessController 
    Route::get('onBoardDevice', [BusinessController::class, 'onBoardDevice'])->name('onBoardDevice');
    Route::post('Business/adddevice', [BusinessController::class, 'adddevice'])->name('Business/adddevice');
    Route::resource('Business', BusinessController::class);
    Route::post('select', [BusinessController::class, 'checkvehicle'])->name('ajax.checkvehicle');
    Route::post('select1', [BusinessController::class, 'checkDevice'])->name('ajax.checkDevice');
    Route::post('select3', [BusinessController::class, 'checkUser'])->name('ajax.checkUser');
    Route::post('select2', [BusinessController::class, 'getGroup'])->name('ajax.getGroup');
    Route::post('Business/batchSale', [BusinessController::class, 'batchSale'])->name('Business/batchSale');
    // Route::post('Business/adddevice', BusinessController::class,'adddevice');

    //billing
    Route::resource('Billing', VdmBillingController::class);
    Route::get('billing/prerenewal', [VdmBillingController::class, 'preRenewal'])->name('billing/prerenewal');
    Route::get('billing/preRenewalList', [VdmBillingController::class, 'preRenewalList'])->name('billing/preRenewalList');
    Route::get('billing/expired', [VdmBillingController::class, 'expiredList'])->name('billing/expired');
    Route::get('billing/convert', [VdmBillingController::class, 'licConvert'])->name('billing/convert');
    Route::post('convert/update', [VdmBillingController::class, 'licUpdate']);

    Route::get('billing/Renewal/{param}', [VdmBillingController::class, 'renewal']);
    Route::get('billing/Cancel/{param}', [VdmBillingController::class, 'LicenceCancel']);
    Route::post('licence/search', [VdmBillingController::class, 'licSearch']);

    // ExcelController
    Route::resource('Excel', ExcelController::class);
    Route::post('import/Excel', [ExcelController::class, 'importExcel'])->name('import/Excel');
    Route::post('downloadExcel/xls', [ExcelController::class, 'downloadExcel'])->name('downloadExcel/xls');
    Route::post('import/DealerExcel', [ExcelController::class, 'importDealerExcel'])->name('import/DealerExcel');
    Route::post('downloadDealerExcel/xls', [ExcelController::class, 'downloadDealerExcel'])->name('downloadDealerExcel/xls');

    // RemoveController
    Route::resource('Remove', RemoveController::class);
    Route::post('Remove/removedevices', [RemoveController::class, 'removedevice'])->name('Remove/removedevices');
    Route::post('select4', [RemoveController::class, 'checkvehicle'])->name('ajax.checkvehicle1');
    Route::post('select5', [RemoveController::class, 'checkDevice'])->name('ajax.checkDevice1');

    // onboard devices and VdmVehicleViewControllre
    Route::resource('vdmVehiclesView', VdmVehicleViewController::class);
    Route::get('vdmVehicles/move_vehicle/{param}', [VdmVehicleViewController::class, 'move_vehicle']);
    Route::post('vdmVehicles/moveVehicle', [VdmVehicleViewController::class, 'moveVehicleUpdate']);
    Route::get('vehicleStatus', [VdmVehicleViewController::class, 'vehicleStatus'])->name('vehicleStatus');
    Route::get('vehicleStatusXls', [VdmVehicleViewController::class, 'vehicleStatusXls'])->name('vehicleStatusXls');
    // Calibrate Excel
    Route::post('export/calibrate', [VdmVehicleViewController::class, 'exportExcel'])->name('export/calibrate');
    Route::post('import/calibrate', [VdmVehicleViewController::class, 'uploadCalibrate'])->name('import/calibrate');
    Route::post('export/autocalibrate', [VdmVehicleViewController::class,'downloadAutoCalibrate'])->name('downloadAutoCalibrate');


    ///onboard search
    Route::resource('DeviceScan', DeviceControllerScan::class);
    Route::get('deviceMove{param}', [DeviceControllerScan::class, 'movedVehicle']);
    Route::get('DeviceScan/sendExcel', [DeviceControllerScan::class, 'sendExcel']);

    Route::get('vdmVehicles/changeExpireDate', [VdmVehicleController::class, 'changeExpireDate']);

    // VdmVehicleController
    Route::get('vdmVehicles/dealerSearchModel', [VdmVehicleController::class, 'dealerSearchModel'])->name('vdmVehicles/dealerSearchModel');
    Route::get('vdmVehicles/dealerSearch', [VdmVehicleController::class, 'dealerSearch'])->name('vdmVehicles/dealerSearch');

    Route::post('vehicleList', [VdmVehicleController::class, 'vehicleListAjax'])->name('ajax.vehicleList');
    Route::post('vehicleStatus', [VdmVehicleViewController::class, 'vehicleStatusAjax'])->name('ajax.vehicleStatus');
    Route::post('vdmVehicles/findDealerList', [VdmVehicleController::class, 'findDealerList'])->name("vdmVehicles/findDealerList");

    Route::resource('vdmVehicles', VdmVehicleController::class);
    Route::get('vdmVehicles/edit/{param1}', [VdmVehicleController::class, 'edit']);
    Route::get('vdmVehicles/stops/{param}/{param1}', [VdmVehicleController::class, 'stops']);
    Route::get('vdmVehicles/removeStop/{param}/{param1}', [VdmVehicleController::class, 'removeStop']);
    Route::get('vdmVehicles/migration/{param1}', [VdmVehicleController::class, 'migration']);
    Route::post('vdmVehicles/migrationUpdate', [VdmVehicleController::class, 'migrationUpdate'])->name('migrationUpdate');
    Route::post('vdmVehicles/generate', [VdmVehicleController::class, 'generate']);
    Route::post('vdmVehicles/moveDealer', [VdmVehicleController::class, 'moveDealer']);
    // rename device
    Route::get('vdmVehicles/rename/{param}', [VdmVehicleController::class, 'rename']);
    Route::post('vdmVehicles/renameUpdate', [VdmVehicleController::class, 'renameUpdate']);
    // calibrateType
    Route::get('vdmVehicles/calibrate/{vid}/{count?}', [VdmVehicleController::class, 'calibrateType'])->name('calibrate');
    Route::post('vdmVehicles/calibrateUpdate', [VdmVehicleController::class, 'calibrateTypeUpdate'])->name('calibrateUpdate');
    Route::post('calibrateget', [VdmVehicleController::class, 'calibrateGet'])->name('ajax.calibrateget');

    Route::get('vdmVehicles/create/{param1}', [VdmVehicleController::class, 'create']);

    // s
    Route::get('vdmVehicles/calibrateOil/{param}', [VdmVehicleController::class, 'calibrate']);

resources/views/vdm/vehicles/calibrate_sensorList.blade.php
<style>
.topnav {
  overflow: hidden;
  background-color: #2fd0c1;
  overflow: hidden;
  border-radius: 17px;
}

.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #111;
  color: black;
}
.btn-inf{
  background-color: #ffb606;
    border-color: #ffb606;
    color: #FFFFFF;
}
.active {
    background-color: #3a8a83;
    color: #34455eb8;
}

.topnav .icon {
  display: none;
}

@media screen and (max-width: 600px) {
  .topnav a:not(:first-child) {display: none;}
  .topnav a.icon {
    float: right;
    display: block;
  }
}

@media screen and (max-width: 600px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
}
</style>

<div class="topnav" id="sensorConfig">
@for($j=1;$j<=$numberofSensorColumn;$j++)
  <a id="sensor<?php echo $j ?>" onclick="getvalues1('<?php echo $vehicleId ?>','<?php echo $j ?>')" style="margin-left: 1%;color:white;">Sensor <?php echo $j ?></a>
@endfor
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>
function myFunction() {
    var x = document.getElementById("myTopnav");
    if (x.className === "topnav") {
        x.className += " responsive";
    } else {
        x.className = "topnav";
    }
}
  
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});

function getvalues1(vehicle,sensorId)  {
//  alert(" Hai "+vehicle+" sensorId "+sensorId);
  //'vdmVehicles/calibrateOil/' . $
  var formAction = "../"+vehicle+'&'+sensorId+"/1";
		window.location =  formAction;  
}



</script>

resources/views/vdm/vehicles/dashboard.blade.php
@extends("layouts.app")
@section('content')
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">@lang('messages.Dashboard')</h4>
            <ul class="breadcrumbs">
                <li class="nav-home">
                    <a href="#">
                        <i class="flaticon-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">@lang('messages.Dashboard')</a>
                </li>
            </ul>
        </div>
        <div class="page-body">
            <div class="row row-card-no-pd mt--2">
                <div class="col-sm-6 col-md-4">
                    <div class="card card-stats card-round">
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-5">
                                    <div class="icon-big text-center">
                                        <i class="fas fa-truck text-danger"></i>
                                    </div>
                                </div>
                                <div class="col-7 col-stats">
                                    <div class="numbers">
                                        <p class="card-category">
                                            @lang('messages.TotalVehiclesOnBoard')
                                        </p>
                                       <h4 class="card-title text-center">{{ $count }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <div class="card card-stats card-round">
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-5">
                                    <div class="icon-big text-center">
                                        <i class="fas fa-calendar-alt text-danger"></i>
                                    </div>
                                </div>
                                <div class="col-7 col-stats">
                                    <div class="numbers">
                                        <p class="card-category">@lang('messages.ThisMonth')</p>
                                        <h4 class="card-title text-center">{{ $prsentMonthCount }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <div class="card card-stats card-round">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-5">
                                    <div class="icon-big text-center">
                                        <i class="fas fa-calendar-alt text-danger"></i>
                                    </div>
                                </div>
                                <div class="col-7 col-stats">
                                    <div class="numbers">
                                        <p class="card-category">@lang('messages.LastMonth')</p>
                                        <h4 class="card-title text-center">{{ $prevMonthCount }} </h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card animated zoomIn">
                <div class="card-body">
                    <div class="card-title text-primary">@lang('messages.VehiclesOnBoardwitheachDealers')</div>
                    <div class="row mt-4">
                        <div class="col-12  overflow-auto">
                            <table id="example1"
                                class="display table table-striped table-hover w-100 table-head-bg-primary dataTable no-footer">
                                <thead class="thead-light">
                                    <tr>
                                        <th style="text-align: center;">@lang('messages.DealerID')</th>
                                        <th style="text-align: center;">@lang('messages.NumberOfVehicles')</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (isset($dealerId))
                                        @foreach ($dealerId as $key => $value)
                                            <tr style="text-align: center; font-size: 11px;">
                                                <td> {{ Form::label('li', $key) }}</td>
                                                <td> {{ Form::label('l', $value . ' ' . ' ') }}</td>
                                            </tr>
                                        @endforeach
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/vdm/vehicles/dealerSearch.blade.php
@extends("layouts.app")
@section('content')
    <div id="wrapper">
        <div class="content animated zoomIn">
            <div class="page-inner">

                <div class="hpanel">
                    @if (session()->has('message'))
                        <p class="alert {{ session()->get('alert-class', 'alert-warning') }}">
                            {{ session()->get('message') }}
                        </p>
                    @endif
                    <div class="page-body">
                        <div class="card">
                            <div class="card-header">
                                @lang('messages.SelecttheDealername')
                            </div>
                            <div class="card-body">
                                <span class="text-danger error-message">
                                    {{ HTML::ul($errors->all()) }}
                                </span>
                                {{ Form::open(['url' => 'vdmVehicles/findDealerList']) }}
                                <div class="row">
                                    <div class="col-md-4"></div>
                                    <div class="col-md-2">
                                        {{ Form::label('dealerId', __('messages.DealersId').':', ['class' => 'font-weight-bold']) }}
                                    </div>
                                    <div class="col-md-3">
                                        <div class="select2-input">
                                            {{ Form::select('dealerId', $dealerArr, request()->old(''), ['class' => 'form-control selectpicker', 'data-live-search ' => 'true']) }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-center pt-4">
                                        {{ Form::submit('Submit', ['class' => 'btn btn-md btn-primary']) }}
                                    </div>
                                </div>
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script type="text/javascript">
        $(function() {
            $('.selectpicker').select2();
        });
    </script>
@endpush

resources/views/vdm/vehicles/migration.blade.php
@extends('layouts.app')
@section('content')

    <div id="wrapper">
        <div class="content page-inner">
            <div class="hpanel">

                <div class="page-header">
                    <div class="page-title">
                        @lang('messages.VehicleMigration')
                    </div>
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('vdmVehicles.index') }}">
                                @lang('messages.VehicleList')
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">
                                @lang('messages.VehicleMigration')
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">{{ $vehicleId }}</a>
                        </li>
                    </ul>
                </div>
                @if (session()->has('message'))
                    <p class="alert {{ session()->get('alert-class', 'alert-success') }}">
                        {{ session()->get('message') }}
                    </p>
                @endif
                <div class="page-body">
                    <div class="card animated zoomIn">
                        <div class="card-header">
                            <p class="h3">
                                @lang('messages.VehicleMigration')
                            </p>
                        </div>
                        <div class="card-body">
                            <span class="text-danger error-message">
                                {{ HTML::ul($errors->all()) }}
                            </span>
                            {{ Form::open(['url' => route('migrationUpdate'), 'id' => 'testForm']) }}
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-2">
                                        {{ Form::label('vehicleId', __('messages.AssetId/VehicleId') . ' :') }}</div>
                                    <div class="col-md-4">
                                        {{ Form::text('vehicleId', $vehicleId, ['class' => 'form-control ', 'required' => 'required', 'id' => 'vehicleId']) }}
                                        {{ Form::hidden('vehicleIdOld', $vehicleIdOld, ['class' => 'form-control']) }}
                                        {{ Form::hidden('deviceIdOld', $deviceIdOld, ['class' => 'form-control']) }}
                                        {{ Form::hidden('expiredPeriodOld', $expiredPeriodOld, ['class' => 'form-control']) }}
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-2">
                                        {{ Form::label('deviceId', __('messages.DeviceId/IMEINo') . ' :') }}</div>
                                    <div class="col-md-4">
                                        {{ Form::text('deviceId', $deviceId, ['class' => 'form-control caps', 'required' => 'required', 'id' => 'deviceId']) }}
                                    </div>
                                </div>
                                <br>
                                <div class="row mt-3">
                                    <div class="col-md-12 text-center">
                                        <a class="btn btn-danger" href="{{ URL::to('VdmVehicleScan' . $vehicleId) }}">
                                            @lang('messages.Cancel')
                                        </a>
                                        {{ Form::submit(__('messages.MigrateVehicle'), ['class' => 'btn btn-primary']) }}

                                    </div>

                                </div>
                            </div>
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection
@push('js')
    <script type="text/javascript">
        $('#testForm :submit').attr('disabled', true);
        $("#testForm input").one('change keydown', function() {
            $('#testForm :submit').attr('disabled', false);
        })
        $('#vehicleId').on('change', function() {
            $("#span1").text("");
        });
        $('#deviceId').on('change', function() {
            $("#span2").text("");

        });
        $('#testForm').on('submit', function(e) {
            var minLength = 5;
            var maxLength = 30;
            var submit = true;
            var datas = {
                'vehicleId': $('#vehicleId').val(),
                'deviceId': $('#deviceId').val()
            }
            if (datas.vehicleId.length < minLength) {
                $('#vehicleId').aftererr('Vehicle Id is short');
                submit = false;
            }
            if (datas.deviceId.length < minLength) {
                $('#deviceId').aftererr('Device Id is short');
                submit = false;
            }
            return submit;
        });
    </script>
@endpush

resources/views/vdm/vehicles/stopgenerate.blade.php
@extends('layouts.app')
@section('content')

    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">
                @lang('messages.GenerateStops')
            </h4>
            <ul class="breadcrumbs">
                <li class="nav-home">
                    <a href="#">
                        <i class="flaticon-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="{{ route('vdmVehicles.index') }}">
                    @lang('messages.VehicleList')
                    </a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">
                        @lang('messages.GenerateStops')
                    </a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">{{ $vehicleId }}</a>
                </li>
            </ul>
        </div>
        @if (session()->has('message'))
            <p class="alert {{ session()->get('alert-class', 'alert-success') }}">
                {{ session()->get('message') }}</p>
        @endif

        <div class="page-body">
            <div class="card ">
                <div class="card-body">
                    <span class="text-danger error-message"> {{ HTML::ul($errors->all()) }}</span>
                    {{ Form::open(['url' => 'vdmVehicles/generate']) }}
                    <h3 class="text-primary">
                       @lang('messages.General')
                    </h3>
                    <hr>
                    <div class="row p-2">
                        <div class="col-md-6 form-group">
                            {{ Form::label('vehicle', __('messages.VehicleId')) }}
                            {{ Form::label('vehicleId', $vehicleId, ['class' => 'form-control', 'disabled' => 'disabled']) }}
                            {{ Form::hidden('vehicleId', $vehicleId) }}
                        </div>
                        <div class="col-md-6 form-group">
                            {{ Form::label('Date', __('messages.Date')) }}
                            {{ Form::text('date', request()->old('date'), ['id' => 'calendar', 'placeholder' => 'dd-mm-yyyy', 'class' => 'form-control date', 'required' => 'required']) }}
                        </div>
                        <div class="col-md-6 form-group">
                            {{ Form::label('spd', __('messages.Speed')) }}
                            {{ Form::select('type', ['0' => 'Strict', '5' => 'Medium', '10' => 'Relax'], request()->old('type'), ['class' => 'form-control']) }}
                        </div>
                        <div class="col-md-6 form-group">
                            {{ Form::label('demo', __('messages.Type')) }}
                            {{ Form::text('demo', $demo, ['class' => 'form-control', 'readonly' => 'true']) }}
                        </div>
                    </div><br>
                    <h3 class="text-primary">
                        @lang('messages.StartEndTime')
                    </h3>
                    <hr>
                    <div class="row p-2">
                        <div class="col-md-6 form-group ">
                            {{ Form::label('MST', __('messages.MorningStartTime')) }}
                            {{ Form::text('mst', request()->old('mst'), ['placeholder' => 'Hour : Min', 'class' => 'form-control time', 'required' => 'required']) }}
                        </div>
                        <div class="col-md-6 form-group ">
                            {{ Form::label('MET', __('messages.MorningEndTime')) }}
                            {{ Form::text('met', request()->old('met'), ['placeholder' => 'Hour : Min', 'class' => 'form-control time', 'required' => 'required']) }}
                        </div>
                        <div class="col-md-6 form-group ">
                            {{ Form::label('EST', __('messages.EveningStartTime')) }}
                            {{ Form::text('est', request()->old('est'), ['placeholder' => 'Hour : Min', 'class' => 'form-control time', 'required' => 'required']) }}
                        </div>
                        <div class="col-md-6 form-group">
                            {{ Form::label('EET', __('messages.EveningEndTime')) }}
                            {{ Form::text('eet', request()->old('eet'), ['placeholder' => 'Hour : Min', 'class' => 'form-control time', 'required' => 'required']) }}
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col-md-3 mx-auto">{{ Form::submit(__('messages.Submit'), ['class' => 'btn btn-primary']) }}
                        </div>
                    </div>
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>

    </div>
@endsection
@push('js')
    <script>
        $(function() {
            $(".date").datepicker({
                format: 'DD-MM-YYYY',
            });
            $('.time').timepicker();
        });
    </script>
@endpush